version: '3.8'
services:
  backend:
    build: ./
    image: miracle-backend
    container_name: miracle-backend
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=miracle_service

  db:
    image: postgres:14.5-alpine
    container_name: miracle_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres


  frontend:
    image: miracle-frontend
    container_name: miracle-frontend
    build:
      context: ../../miracle-app
#      dockerfile: ../../miracle-app/Dockerfile
    volumes:
      - ../../miracle-app:/app
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development


  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
#    depends_on:
#      - frontend
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#  miracle-app-frontend:
#    image: miracle-app-frontend:latest
#    environment:
#      PORT: 3000
#      PROXY_API: http://localhost:8080/
#    ports:
#        - "3000:3000"

